apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mlzoomcamp-eks-1 #name of the cluster
  region: ap-southeast-1

nodeGroups: # for our case, we need only one node group (CPU)
  - name: ng-m5-xlarge
    instanceType: m5.xlarge
    desiredCapacity: 1